name: Bug Report
description: Report a problem you're having
body:
  - type: input
    id: version
    attributes:
      label: Fishstrap Version
      description: "What version of Fishstrap are you using?"
      placeholder: "v2.9.0.0"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What problem did you encounter?
      description: Provide a good description of the problem you're having. Screenshots too please.
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: How do you reproduce the problem?
      description: Write down steps to cause the problem, from start to finish, if you can.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
  - type: textarea
    id: log
    attributes:
      label: Fishstrap Log
      description: If you're getting a Fishstrap Exception error, upload your log file here. Otherwise, just leave it empty.
      value: "N/A"
      render: text
